language: ruby
sudo: false
rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
gemfile:
  - gemfiles/activesupport_4.0.gemfile
  - gemfiles/activesupport_4.1.gemfile
  - gemfiles/activesupport_4.2.gemfile
  - gemfiles/activesupport_5.0.gemfile
  - gemfiles/activesupport_5.1.gemfile
script:
  - bundle exec rake
branches:
  only:
    - master
matrix:
  exclude:
  - rvm: 2.0.0-p648
    gemfile: gemfiles/activesupport_5.0.gemfile
  - rvm: 2.0.0-p648
    gemfile: gemfiles/activesupport_5.1.gemfile
  - rvm: 2.1.10
    gemfile: gemfiles/activesupport_5.0.gemfile
  - rvm: 2.1.10
    gemfile: gemfiles/activesupport_5.1.gemfile
  - rvm: 2.4.3
    gemfile: gemfiles/activesupport_4.0.gemfile
  - rvm: 2.4.3
    gemfile: gemfiles/activesupport_4.1.gemfile
  - rvm: 2.5.0
    gemfile: gemfiles/activesupport_4.0.gemfile
  - rvm: 2.5.0
    gemfile: gemfiles/activesupport_4.1.gemfile
